var macro;
var loopCount = 200;
var b = "\n";
var path;

var namesArray0 = ['00o0','010997','01bassi','01fm','021leow','07connor07','0969796981','0btx0','0kfiil','0llie-s','0ptimal_techno','0technology0','0xamusic','0zge','100beatproductions','1010tenten','118bpmrules','11clouds','1200a','122bpm','123678910','123dinamix','123kenzo','123szita','12inchvinyl','13petrovich13','13th-hour-a-m','14crash','15-pro-mastering','1623wolf','17branches','180degrade','187spencer','1904produktionz','1981','1988amr','19962402','1996mab','19rayroman87','19tomdavids94','1enek','1mx','1ndig0','1sma3l-mussa','1spark','1techno','1xtra-by-nightparty','2-face','2-shea','200deep','20onemusic','2257ad','27-announce','2ble','2brain-official','2celebratemusic','2disco','2dope4youbro','2funky2funk','2homies','2hypee','2k-music-producers','2lanes','2rabu','2shaydes','2stepfwd','2xml','3-knuckles-deep','3078','320bpm','320kbps','33a','33reveries','3aref','3catsdeep','3hilary-3','3icky','3leish','3li_h','3nginemusic','3puten','3ronski','3scompany','3somevibes','420weeneed','45-k0','47action','4byfour','4eggz','4m1','4micmusic','4ngus-channel','4rglasgow','4t50c','4th-dimension-club','4uproject','4_1000','50-vodou-digitals','50k','5435567869','5477564','55-1p','551992','5ambo-1','5ctt','5eighty6','5floors','5kraken5','5plendor','5tatech-narsilion','666_connection','671jcp','69michaelchrist','6channels','6co-m3d1n4','6napse','6yay','773609','7evnup','7h30min','8000000jules','80nk','80pleierkasten80','8618312','863133628','86woods','888riddim888','88lah88','89proposal','8day-montreal','8inhole','90degreessound','915-night-life','9er','9thousand9','9_t_1','a-ap-naffy','a-buz','a-d-d_child','a-diguer','a-drex','a-evaa','a-flo','a-gonzalez','a-hernandez-muzik','a-hunter','a-l-i-s-e-d-e-e','a-lamet-1','a-m-i-n-1','a-mari','a-pelch','a-pop','a-schneider','a-v-a-n','a-v-m','a-viktor-kovacs','a-y-d-marinac','a-_tech','a1meusick','aa5','aabramov','aadz-loonat','aaguiar','aalbir','aames_ro','aamgiessen','aaray76','aargenal','aaron-arding','aaron-ben','aaron-d-2','aaron-elfassy','aaron-saenz','aaron-sanchez-fonseca','aaron-ting-1','aaron-ward','aaronbeko','aaronjsavage','aaronpezzaniti','aaronpitfield2'];
var alreadyNames = ['aaronstix','aaronswales','aaronxben','aaron_brooks','aaron_carr','aarsavage','aaval1','aaxi','aaz3','ab-420','abacha','abadiojr','abato96','abcmusks','abdelhamid-tebourbi','abdoulie-bobinski-jallow','abdu-4','abdul-wahab-sheikh','abdullah-ali-7','abe-van-dam','abedpocketwatch','abel-blanes','abel-ven','abelmezzomo','abelsolano','abendroth-1','abiboysilence','abigbabyd','abilic','abitual','abjure','ablywinter','abna-1','aboudhussein','aboutblank-music','aboutclint','aboutjack','abouttoblow','aboyd','abr0','abrasiv','absent','absolud_joy3','absolut-konrad','absolute-bassline','absolutjm','abstergo-industries','abstractsyence','abstrhytmik','absynthek','ac204','ac3falia','access1','acdktt','ace-paradise','acemetrik','ace_pilot','achalkhanolkar','achist90','achrefmemories','achtmensch','achwas'];

var namesArray1 = ['acid-aj','acid-dog214','acidbuddhamusic','acidfonk','acidjunk-2','acidpc','acidwizard23','ackenss','acki-1','ackwyer','acmayc','acmme','acrofunkzmusic','acruniamusic','activelinesix','ad-2','ad-am-9','ada-rub','adacrom','adagio-system','adakt','adalidedd','adam-ball','adam-barthelson','adam-fletcher-1','adam-harriman','adam-kelly1','adam-lombardo','adam-paton','adam-prendergast','adam-ridge-1','adam-roofy','adam-sandford-1','adam-wumm','adamanthony','adambence','adambray','adambreaks','adamcoley','adamcurtain','adamengstrom','adamhusa','adamhyjek','adamloveee','adamneunfinger','adamp81','adamrjcarey','adamross-1','adamson911','adamsouthdj28','adamthegoose','adamthomas-1','adamtouch','adamvanderveer','adamwakemoore','adan-reid','adarsound','adassa-j','addictbass','addicted2club','addiktionscout','addiment','addouli','adela-mincea','adelaidefisse','adelemoss','adelesicarius','adeli-live','adelina-todorova','adelinalopez','adeloid','adeluxe','ademantine','adermeister','adeshbanvait','adevil-1','adham-magdy','adhd','adi-biluta','adi-v','adieromusic','adigali','adiii','adikt-rivera','adilnadeem15','adio-vita','adipurplepitch','aditodoran','aditude','adi_rtr','administrator77-1','admin_basic','admnti','admonic','adnanh1988','adnanoomer','ado','adog13','adolfo-fdz','adon-baldachino','adonov_official','adorno','adreinmusic','adren-alin','adrenaline-1','adri-n-postiguillo-giraldos','adriaduch','adriakgroovy','adrian-barron-official','adrian-berger','adrian-cristiann','adrian-donadel','adrian-fabregas','adrian-flux','adrian-kiliszek','adrian-perez-u','adrian-stoot','adrian-suter-1'];

///////////////
///////////////////////////////////////////// início 19:48
///////////////
var namesArray = ['petenash','lizzle101','craigo-3','marcbover','polsteam-beluga','phlawd','dj-panache','mr-moutarde','gregward1985','tobberh','jack102','liesurgic-1','muhrad','bahri-jaafer','house_head77','lincoln-eloy','niffaragua','bumani','marco-grosso-dj','handall','kevin-es','michael-davill','midcitymusic','hoobajoob','ezwell','fierceness','yosuecaban','mike-dowson','insteereo','moneyhouseclub','kramertheimmortal','leopoldo-carbonara','djdrigoargentina','effujeff','zoetkoekske','hotrodhillis','lukebfox','sergiomaruki','macaulay-mcgrath','zeron_b','srslystoned','iv-an-2','t-dech','h-ich','olenkadataw','unclesand','joshel79','mcmxcmade','mr-sativo','golikov','talohana','stephanc','geerken','nondejul','indahue','verlustfrei','michael-clifford-dj','frahgtrapn','internal_perception_rec','david-t-2','kennnygan','emiliosafredo','musicolora','anspiua','andersonclaro','lebassdevil','zebpa','dj-u-ree','blanblan-1','ratsk1','immmmmm','wisdom_water','ilias-pilatos','flashlights','lectrob','dalop','loui5dinkgrefe','suendikat','lukas-trunk','pol-doe','onuur','joshua-ranner','anejath-rao','wesleyrazzy','themusicbrewery','alex-key','bruno-pellini','sergey-berlin','julien_martins','tomas-ibacache','info-133','deepdubdidu','anton-hadjiev','ante-mortem','iki-15','maycol-de-jesus','dj-tori-neuro','antony-colanardi','janeman','feieroniiguana','aintnobodymusictoolkit','dirtypunk','dlbdnb','witek','mchinga','ryantc92','svcks','nose_alone','soul_game','fransanchez88','rubiales','jerome1975','thewillersbrothers','sdemey','marko-maegi','louis-emile-1','themightydude','tijn-3','zockelwestwoodhood','jeff-moore','fiido12','phantasmo-1','jason-isavadj','kirill-sazanov','hendrikson81','hifi-n-lofi','morrigan-mat-mara','dabmaia','harriscas','maxim-dudakov','chargammon','florispameijer','trevor-oneil','djcira','djcharliewhite90','mikaileraslan','christophercole','icedub','werner_b','adigali','mrbrandonita','augustbetancourt','euch-bouvs','cortes','schubwerk','zabi-general','naka-changu-kongu','marjan-g','david-pulido-1','fefo-3-1','cof-cof','andreiticau','w-o-j-o','lukepard','blacksun-1','gianluca-valvasori','setembre72','milkfrom1989','morgan-goetghebeur','lobertofficial','pvisvikis','mikeybeats','georgeustommy','lolhammond','al-b','thetrinderbrothers','jodie-deep-tech','pitorke','daniali89','orion-mole','djsaw-sets','innoxiia','sflex','z1-deepart','equaldose','pinheads','phips-3','djanepatricia','plan-b-3','mauro-santijara-milo'];

function resetCode() {
    macro = "CODE:";
    macro += "SET !ERRORIGNORE YES" + b;
    macro += "VERSION BUILD=8820413 RECORDER=FX" + b;
}

for (var i = 0; i < namesArray.length; i++) {
//for (var i = 0; i < 3; i++) {
    resetCode();
    macro += 'URL GOTO=http://soundcloud.com/' + namesArray[i] + b;
    macro += 'WAIT SECONDS=2' + b;
    macro += 'TAG POS=1 TYPE=BUTTON ATTR=TXT:Seguir' + b;
    macro += 'WAIT SECONDS=2' + b;
    iimDisplay(i);
    iimPlay(macro);
    if(i==namesArray.length-1) {
    	 iimDisplay('End proccess at ' + new Date().getHours() + ':' + new Date().getMinutes());
    }
}
